### PR TITLE
Some Useful Android Tasks

### PR DESCRIPTION
**Pull request by nickwph**

### CODE REVIEW

**Comment by nickwph** [comment]
@seyeojumu how do we test these tasks?

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by thekushpatel** [comment]
These are some seriously awesome additions! Super useful tasks :)

As for testing, I don't have much experience in testing with node, but I do know that screwdriver has a similar architecture, and they are testing their tasks. If i remember correctly, they just pass in mock parameters into the Task.execute method. Looking at their repo might be good guidance.

**Comment by nickwph** [comment]
@thekushpatel maybe let's merge it?

**Pull request merged**
